"""Domain predictor — L0a in the moe-l2 architecture.

Phase 2: keyword matching for domain prediction + per-layer
domain→expert ID mapping loaded from Phase 1 analysis data.

Architecture:
  1. predict(prompt) → domain label  (keyword-based)
  2. domain_to_expert_ids(domain, layer) → list of expert IDs
  3. get_preload_set(domain) → all expert IDs for all layers

The mapping is loaded from domain_expert_map.json, generated by
`moe_l2/data/generate_expert_map.py` from LLAMA_EXPERT_LOG=1 data.
"""

from __future__ import annotations

import json
import os
from typing import Optional

__all__ = [
    "DOMAINS",
    "predict",
    "predict_hybrid",
    "domain_to_expert_ids",
    "get_preload_set",
    "get_backbone_experts",
    "get_layer_specificity",
    "load_mapping",
    "is_semantic_available",
    "is_tfidf_available",
    "enable_tfidf",
]

# ── Default domain list — matches the 8 tested domains ──
DOMAINS = [
    "codegen",
    "debug",
    "math",
    "logic",
    "general_qa",
    "chinese_tech",
    "creative_write",
    "translate",
]

# ── Keyword → domain mapping ──
# Based on Phase 1 test prompts + common patterns for each domain.
# All keywords use word-boundary awareness in predict() — single short tokens
# like "log" or "api" are suffixed with a space to avoid false substring matches.
_KEYWORD_MAP: dict[str, str] = {
    # ── codegen ──
    "write a function": "codegen",
    "implement ": "codegen",
    "def ": "codegen",
    "class ": "codegen",
    "rest api": "codegen",
    "web server": "codegen",
    "http server": "codegen",
    "api ": "codegen",
    "script": "codegen",
    "import ": "codegen",
    "const ": "codegen",
    "sorting": "codegen",
    "algorithm": "codegen",
    "function that": "codegen",
    "python code": "codegen",
    "javascript": "codegen",
    "write code": "codegen",
    "snippet": "codegen",
    "crud": "codegen",
    "sql query": "codegen",
    "database schema": "codegen",
    "dockerfile": "codegen",
    "generate ": "codegen",
    "print ": "codegen",
    "multiply": "codegen",
    "matrix multiplication": "codegen",
    # ── debug ──
    "error": "debug",
    "bug": "debug",
    "crash": "debug",
    "fix ": "debug",
    "traceback": "debug",
    "exception": "debug",
    "not working": "debug",
    "segmentation fault": "debug",
    "debug ": "debug",
    "log ": "debug",
    "stack trace": "debug",
    "runtime error": "debug",
    "typeerror": "debug",
    "keyerror": "debug",
    "attributeerror": "debug",
    "valueerror": "debug",
    "indexerror": "debug",
    "syntaxerror": "debug",
    "broken": "debug",
    "fail": "debug",
    "failed": "debug",
    "unexpected behavior": "debug",
    "crash report": "debug",
    "help debug": "debug",
    # ── math ──
    "calculate": "math",
    "equation": "math",
    "derivative": "math",
    "integral": "math",
    "probability": "math",
    "matrix": "math",
    "solve for": "math",
    "calculus": "math",
    "function f(": "math",
    "f(x)": "math",
    " lim ": "math",
    "integrate": "math",
    "differential": "math",
    "eigenvalue": "math",
    "vector": "math",
    "statistics": "math",
    "regression": "math",
    "numerical": "math",
    "formula": "math",
    "compute ": "math",
    # ── logic ──
    "puzzle": "logic",
    "reasoning": "logic",
    "if and only if": "logic",
    "constraint": "logic",
    "deduction": "logic",
    "logical ": "logic",
    "inference": "logic",
    "syllogism": "logic",
    "premise": "logic",
    "theorem": "logic",
    "proof": "logic",
    "iff ": "logic",
    "implies": "logic",
    "contradiction": "logic",
    "brain teaser": "logic",
    "logic puzzle": "logic",
    "truth table": "logic",
    "boolean": "logic",
    # ── general_qa ──
    "what is ": "general_qa",
    "explain": "general_qa",
    "tell me about": "general_qa",
    "definition": "general_qa",
    "what are ": "general_qa",
    "how does": "general_qa",
    "knowledge": "general_qa",
    "meaning of": "general_qa",
    "describe": "general_qa",
    "overview": "general_qa",
    "difference between": "general_qa",
    "compare ": "general_qa",
    "example of": "general_qa",
    # ── chinese_tech ──
    "是什么": "chinese_tech",
    "怎么": "chinese_tech",
    "原理": "chinese_tech",
    "教程": "chinese_tech",
    "配置": "chinese_tech",
    "部署": "chinese_tech",
    "为什么": "chinese_tech",
    "如何": "chinese_tech",
    "搭建": "chinese_tech",
    "安装": "chinese_tech",
    "使用": "chinese_tech",
    "方法": "chinese_tech",
    "技术": "chinese_tech",
    "架构": "chinese_tech",
    "优化": "chinese_tech",
    "性能": "chinese_tech",
    "框架": "chinese_tech",
    "源码": "chinese_tech",
    "docker": "chinese_tech",
    "linux": "chinese_tech",
    "nvidia": "chinese_tech",
    "gpu": "chinese_tech",
    "llm": "chinese_tech",
    "大数据": "chinese_tech",
    "定理": "chinese_tech",
    "理论": "chinese_tech",
    "证明": "chinese_tech",
    "推导": "chinese_tech",
    "cron": "chinese_tech",
    "setup ": "chinese_tech",
    # ── creative_write ──
    "story": "creative_write",
    "poem": "creative_write",
    "write a story": "creative_write",
    "narrative": "creative_write",
    "fiction": "creative_write",
    "novel": "creative_write",
    "tale": "creative_write",
    "character": "creative_write",
    "plot": "creative_write",
    "imagine ": "creative_write",
    "dialogue": "creative_write",
    "描写": "creative_write",
    "创作": "creative_write",
    "作文": "creative_write",
    "小说": "creative_write",
    "故事": "creative_write",
    "theme": "creative_write",
    # ── translate ──
    "translate": "translate",
    "翻译": "translate",
    "in english": "translate",
    "in chinese": "translate",
    "in japanese": "translate",
    "convert to": "translate",
    "render in": "translate",
    "localize": "translate",
}

# ── Cached mapping ──
_DOMAIN_MAP: dict | None = None

# ── Semantic predictor (optional) ──
_SEMANTIC_PREDICTOR: Optional["SemanticPredictor"] = None

# ── TF-IDF classifier (optional, P2 ①) ──
_TFIDF_PREDICTOR: Optional["TfidfPredictor"] = None

if False:  # TYPE_CHECKING only — avoids runtime import of optional deps
    from .semantic_predictor import SemanticPredictor  # noqa: F401
    from .tfidf_predictor import TfidfPredictor  # noqa: F401


def is_semantic_available() -> bool:
    """Check if the optional semantic predictor is available."""
    try:
        from .semantic_predictor import SemanticPredictor  # noqa: F401
        return True
    except ImportError:
        return False


def is_tfidf_available() -> bool:
    """Check if the trained TF-IDF classifier artifact exists."""
    try:
        from .tfidf_predictor import is_tfidf_available as _check
        return _check()
    except ImportError:
        return False


def enable_tfidf() -> bool:
    """Load the TF-IDF classifier (lazy, requires scikit-learn + trained model).

    Returns True if loaded successfully, False if unavailable
    (sklearn missing or domain_classifier.joblib absent) — callers fall back
    to keyword / semantic prediction.
    """
    global _TFIDF_PREDICTOR
    if _TFIDF_PREDICTOR is not None:
        return True
    try:
        from .tfidf_predictor import TfidfPredictor
        _TFIDF_PREDICTOR = TfidfPredictor()
        return True
    except Exception:
        _TFIDF_PREDICTOR = None
        return False


def enable_semantic(model_name: str = "all-MiniLM-L6-v2") -> None:
    """Enable the optional embedding-based semantic predictor.

    Requires `sentence-transformers` to be installed.
    Downloads all-MiniLM-L6-v2 (~80MB) on first call.
    """
    global _SEMANTIC_PREDICTOR
    if _SEMANTIC_PREDICTOR is not None:
        return
    from .semantic_predictor import SemanticPredictor
    _SEMANTIC_PREDICTOR = SemanticPredictor(model_name=model_name)


def load_mapping(path: Optional[str] = None) -> dict:
    """Load domain→expert mapping from JSON.

    Args:
        path: Path to domain_expert_map.json. Auto-detects if None.

    Returns:
        The parsed mapping dict.
    """
    if path is None:
        path = os.path.join(os.path.dirname(__file__), "data", "domain_expert_map.json")

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"domain_expert_map.json not found at {path}. "
            "Run `python -m moe_l2.data.generate_expert_map` first."
        )

    with open(path) as f:
        return json.load(f)


def _get_map() -> dict:
    global _DOMAIN_MAP
    if _DOMAIN_MAP is None:
        _DOMAIN_MAP = load_mapping()
    return _DOMAIN_MAP


def predict(prompt: str, fallback: str = "general_qa") -> str:
    """Predict domain from prompt text using keyword matching.

    Keywords with trailing spaces are matched as word-boundary-aware
    so 'log ' matches "log file" and "log." but not "logic".
    CJK keywords (Chinese characters) use plain substring match.

    Args:
        prompt: User input text.
        fallback: Domain label when no keywords match.

    Returns:
        Predicted domain label.

    Performance: O(k) where k = number of keywords (~200).
    Runs on CPU, no model call, sub-millisecond.
    """
    prompt_lower = prompt.lower()
    for keyword, domain in sorted(
        _KEYWORD_MAP.items(), key=lambda kv: -len(kv[0])
    ):
        # Trailing-space keywords → word-boundary match
        if keyword.endswith(" "):
            base = keyword.rstrip()
            idx = prompt_lower.find(keyword)
            if idx != -1:
                return domain
            # Also match before punctuation/end-of-string
            idx = prompt_lower.find(base)
            if idx != -1:
                after = prompt_lower[idx + len(base):]
                if not after or not after[0].isalnum():
                    return domain
        else:
            # Plain substring match (mostly CJK or long phrases)
            if keyword in prompt_lower:
                return domain
    return fallback


def predict_hybrid(
    prompt: str,
    fallback: str = "general_qa",
    tfidf_threshold: float = 0.0,
) -> str:
    """Predict domain using keyword matching + TF-IDF classifier + semantic embedding fallback.

    Three-tier prediction:
      1. Fast path: keyword matching (same as predict()).
      2. TF-IDF classifier (P2 ①, ~1-3ms): only when keywords miss AND
         tfidf_threshold=0 (always override) or the linear margin is confident.
      3. Semantic fallback: only when keyword + TF-IDF both miss AND semantic
         predictor is enabled AND its confidence > threshold.

    The semantic predictor uses all-MiniLM-L6-v2 (~80MB) and runs
    ~10-30ms on CPU. It requires `sentence-transformers` installed.

    Args:
        prompt: User input text.
        fallback: Domain label when nothing matches.
        tfidf_threshold: Min decision margin for TF-IDF override (default 0 = always).
    """
    # Fast path: keyword matching
    result = predict(prompt, fallback=fallback)
    if result != fallback:
        return result  # keyword already classified it

    # TF-IDF classifier (P2 ①): trained on collect seed data, zero-download.
    # Only overrides when the linear margin is confident enough.
    if _TFIDF_PREDICTOR is not None:
        tfidf_result = _TFIDF_PREDICTOR.predict(prompt, confidence_threshold=tfidf_threshold)
        if tfidf_result is not None:
            return tfidf_result

    # Slow path: semantic fallback
    if _SEMANTIC_PREDICTOR is None:
        return result  # semantic not enabled

    semantic_result = _SEMANTIC_PREDICTOR.predict(prompt)
    if semantic_result is not None:
        return semantic_result

    return result


def domain_to_expert_ids(domain: str, layer: int) -> list[int]:
    """Return the top-K expert IDs for a given domain and layer.

    Args:
        domain: Domain label (e.g. "codegen", "math").
        layer: Layer index (0-39 for Qwen3.6).

    Returns:
        List of expert IDs (0-255) ordered by frequency in training data.
        Empty list if domain or layer not found.
    """
    mapping = _get_map()
    domain_key = str(layer)

    if domain not in mapping.get("domains", {}):
        return []
    if domain_key not in mapping["domains"][domain].get("per_layer_top", {}):
        return []

    return mapping["domains"][domain]["per_layer_top"][domain_key]


def get_preload_set(domain: str) -> dict[int, list[int]]:
    """Get all per-layer expert lists for a domain.

    Args:
        domain: Domain label.

    Returns:
        Dict of {layer: [expert_ids]} for all layers.
        Used by the L2 cache manager to decide which experts to preload.
    """
    mapping = _get_map()
    if domain not in mapping.get("domains", {}):
        return {}

    result = {}
    for layer_str, experts in mapping["domains"][domain].get("per_layer_top", {}).items():
        result[int(layer_str)] = experts
    return result


def get_backbone_experts() -> list[int]:
    """Return the backbone experts (those in ALL domains' top-K).

    For Qwen3.6 with full data, this is typically empty — each domain
    has distinct top experts. Backbone is most useful for small models
    (like DeepSeek-V2-Lite) or limited data.
    """
    mapping = _get_map()
    return mapping.get("backbone_experts", [])


def get_layer_specificity(layer: int) -> dict | None:
    """Return metadata about domain specificity at a given layer.

    Returns:
        Dict with cross_domain_jaccard, specialist_ratio, or None.
    """
    mapping = _get_map()
    return mapping.get("layer_specificity", {}).get(str(layer))
